# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mongle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.8.2'
pod 'Kingfisher', '~> 5.0'
pod 'SnapKit', '~> 5.0.0'

pod 'Then'
pod 'Hero'
pod 'lottie-ios'
pod 'Gifu'
pod 'SwiftyGif'
  # Pods for Mongle
  
  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
          end
      end
  end
end